### ISSUE TITLE
Keys for end chunks are being rejected?

### ISSUE THREAD

**Issue by NinCollin** [reedacartwright/mcberepair#5]
I wrote some scripts to delete every key beginning with @ (which, to my knowledge, are all chunk keys) except for a long list of chunks (which included overworld, nether, and end keys)

All the areas in the nether and overworld were successfully preserved (confirmed with map editors and physically flying around) 

However, the entire end shows up empty in a map editor (which cannot generate new chunks.) Dumping the list of keys again and using CTRL-F to search for an end chunk I saved (i.e. @2:-17:1:44) confirms the end chunk keys are _still in the world's database_ yet a map editor shows them empty (and Minecraft regenerates them.)

The filesize of the list of chunks to delete + the filesize of the list of chunks to keep = the filesize of the complete chunk list before pruning, so everything _should_ be there, but end chunks are somehow being rejected

It's possible that my bare understanding of this has caused me to somehow omit critical information, but since 2/3 dimensions work, I'm not sure what I could be missing.

**Comment by reedacartwright** [comment]
My guess is that you didn't preserve the right End keys as `@2:-17:1:44` is a nether key. The third element refers to the dimension and. 0 = overworld, 1 = nether, 2 = end.

**Comment by NinCollin** [comment]
Huh, you're right. I was using awk to filter out chunks by dimension id, but I was attempting to search for chunks with a dimension id of -1 (thinking Java style) but it instead pulled chunks from 1 instead (the negative was ignored) so I didn't notice anything was wrong; my chunk list was still being populated, albeit with the wrong data. I knew it had to be some silly mistake on my part hahahaha. Thanks though!
